#!/usr/local/bin/perl
#########
# ProServer DAS Server
# Author:        rmp
# Maintainer:    $Author: andyjenkinson $
# Created:       2003-05-22
# Last Modified: $Date: 2008-09-21 20:05:54 +0100 (Sun, 21 Sep 2008) $
# Source:        $Source: /nfs/team117/rmp/tmp/Bio-Das-ProServer/Bio-Das-ProServer/eg/proserver,v $
# Id:            $Id: proserver 528 2008-09-21 19:05:54Z andyjenkinson $
# $HeadURL: https://proserver.svn.sf.net/svnroot/proserver/trunk/eg/proserver $
#
package proserver;
use lib qw(./blib/lib ../blib/lib . ..);
use Bio::Das::ProServer;
use strict;
use warnings;

our $VERSION = q(2.9);#do { my ($v) = (q$Revision: 528 $ =~ /\d+/mxg); $v; };

Bio::Das::ProServer->run();
0;
